# Generated by Django 2.1.3 on 2019-05-19 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopind', '0002_auto_20190518_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='用户列表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('昵称', models.CharField(blank=True, max_length=50)),
                ('生日', models.DateTimeField(blank=True)),
                ('账户余额', models.DecimalField(decimal_places=2, max_digits=10)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户列表',
                'verbose_name_plural': '用户列表',
                'db_table': '用户列表',
            },
        ),
        migrations.AlterModelOptions(
            name='产品列表',
            options={'ordering': ('-创建时间',), 'verbose_name': '产品列表', 'verbose_name_plural': '产品列表'},
        ),
        migrations.AlterModelOptions(
            name='商品类别表',
            options={'verbose_name': '商品类别表', 'verbose_name_plural': '商品类别表'},
        ),
    ]
