# Generated by Django 2.1.3 on 2019-05-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopind', '0003_auto_20190519_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='用户列表',
            name='账户余额',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
