# Generated by Django 2.1.3 on 2019-05-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopind', '0004_auto_20190519_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='用户列表',
            name='生日',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
